-- Public speaker content follows the free-link/category migrations 010 and 011.
CREATE TABLE speakers (
 id text PRIMARY KEY,
 name text NOT NULL,
 role text NOT NULL,
 organization text NOT NULL,
 image_slug text NOT NULL,
 linkedin text NOT NULL DEFAULT '',
 position integer NOT NULL UNIQUE CHECK(position > 0),
 published boolean NOT NULL DEFAULT true,
 updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO speakers(position,id,name,role,organization,image_slug,linkedin) VALUES
 (1,'jayakrishna-ambati','Dr. Jayakrishna Ambati','Center Director & Professor','University of Virginia Health System','jayakrishna-ambati',''),
 (2,'thirumalachari-ramasami','Dr. Thirumalachari Ramasami','Former Secretary','Department of Science & Technology, Government of India','thirumalachari-ramasami','https://www.linkedin.com/in/thirumalachari-ramasami-b62192175/'),
 (3,'t-p-singh','Prof. T. P. Singh','Distinguished Professor','AIIMS, New Delhi','t-p-singh',''),
 (4,'ron-geyer','Prof. Ron Geyer','Professor, Department of Pathology and Laboratory Medicine','University of Saskatchewan, Canada','ron-geyer','https://www.linkedin.com/in/ron-geyer-69010939/'),
 (5,'shane-miersch','Dr. Shane Miersch','Chief Scientific Officer','Simisco Biologics','shane-miersch','https://www.linkedin.com/in/shane-miersch-89932b9/'),
 (6,'g-m-nair','Prof. G. M. Nair','Director','Kerala Academy of Sciences','g-m-nair',''),
 (7,'beena-pillai','Dr. Beena Pillai','Director','BRIC-Rajiv Gandhi Centre for Biotechnology','beena-pillai','https://www.linkedin.com/in/beena-pillai-99597675/'),
 (8,'raj-shirumalla','Dr. Raj Shirumalla','Mission Director, National Biopharma Mission','BIRAC','raj-shirumalla','https://www.linkedin.com/in/dr-raj-k-shirumalla-25289415/'),
 (9,'b-meenakumari','Dr. B. Meenakumari','Former Chairperson, National Biodiversity Authority','Former Deputy Director General (Fisheries), ICAR','b-meenakumari',''),
 (10,'murali-neelakantan','Murali Neelakantan','Principal Lawyer','Amicus','murali-neelakantan','https://www.linkedin.com/in/muralineelakantan/'),
 (11,'ravi-trivedi','Dr. Ravi Trivedi','Vice President','Zydus Lifesciences','ravi-trivedi','https://www.linkedin.com/in/ravi-kumar-t-2928639/'),
 (12,'jayashankar-das','Dr. Jayashankar Das','Founder & CEO','ELEMENTOZ RESEARCH','jayashankar-das','https://www.linkedin.com/in/dr-jayashankar-das-/'),
 (13,'preveen-ramamoorthy','Preveen Ramamoorthy','Founder & Chief Scientific Officer','T Therapeutics, USA','preveen-ramamoorthy','https://www.linkedin.com/in/preveen-ramamoorthy-818267/'),
 (14,'c-s-mani','Dr. C. S. Mani','Surgical Oncologist','Apollo Hospitals, Chennai','c-s-mani',''),
 (15,'aju-mathew','Dr. Aju Mathew','Oncologist','Kerala Cancer Care, Ernakulam','aju-mathew','https://www.linkedin.com/in/aju-mathew-00b384242/'),
 (16,'ashish-m-kumar','Ashish M. Kumar','Senior Vice President & Cluster Head','Zydus Lifesciences','ashish-m-kumar','https://www.linkedin.com/in/ashish-kumar-43909664/'),
 (17,'aniruddha-bhati','Dr. Aniruddha Bhati','Principal Scientist & Business Lead','Takara Bio','aniruddha-bhati','https://www.linkedin.com/in/aniruddha-bhati/'),
 (18,'girish-chundayil-madathil','Dr. Girish Chundayil Madathil','Co-founder & CEO','Luxmatra Innovations','girish-chundayil-madathil','https://www.linkedin.com/in/girishcm/'),
 (19,'rahul-purwar','Dr. Rahul Purwar','Professor, Department of Biosciences and Bioengineering','Indian Institute of Technology Bombay','rahul-purwar','https://www.linkedin.com/in/rahul-purwar-3187608a/'),
 (20,'p-sanjeev-kumar','Dr. P. Sanjeev Kumar','Former Senior Research Officer, DSU','Government Ayurveda College','p-sanjeev-kumar',''),
 (21,'vinodh-kumar-adithya','Vinodh Kumar Adithya','Co-founder','Capla GmbH, Germany','vinodh-kumar-adithya','https://www.linkedin.com/in/adithyaavka/'),
 (22,'s-chandrashekaran','Dr. S. Chandrashekaran','Founder, Chairman & Managing Director','Vipragen Biosciences','s-chandrashekaran',''),
 (23,'vinaya-k-k','Dr. Vinaya K. K.','Head of R&D Operations','WellGenome Biotechnology','vinaya-k-k',''),
 (24,'sujith-subash-eranezhath','Sujith Subash Eranezhath','Chief Executive Officer, iCAINE','All India Institute of Ayurveda, New Delhi','sujith-subash-eranezhath','https://www.linkedin.com/in/sujitheranezhath/'),
 (25,'yadu-narayanan-mooss','Dr. Yadu Narayanan Mooss E. T.','Executive Director','Vaidyaratnam Group','yadu-narayanan-mooss',''),
 (26,'sreekumar-appukuttan-nair','Dr. Sreekumar Appukuttan Nair','Chairman & Director','Wellness Solutions','sreekumar-appukuttan-nair','https://www.linkedin.com/in/dr-sreekumar-appukuttan-nair-06511a20/'),
 (27,'siddharth-m-joshi','Dr. Siddharth M. Joshi','Associate Vice President','LTM, Mumbai','siddharth-m-joshi',''),
 (28,'v-a-george','Dr. V. A. George','Executive Chairman','Thejo Engineering, Chennai','v-a-george','https://www.linkedin.com/in/george-antony-vadakkekara-09907518/'),
 (29,'harkaran-dhingra','Harkaran Dhingra','Chief Executive Officer','DSS Takara Bio India','harkaran-dhingra','https://www.linkedin.com/in/harkaran-dhingra/'),
 (30,'ajitesh-harihar-lunge','Dr. Ajitesh Harihar Lunge','Co-founder & CEO','Locksmith Bio','ajitesh-harihar-lunge',''),
 (31,'vaidya-m-prasad','Dr. Vaidya M. Prasad','Director','Sunethri Ayurvedashramam, Thrissur','vaidya-m-prasad',''),
 (32,'mahesh-iyer','Dr. Mahesh Iyer','Head of Data and Quantitative Sciences','Bristol Myers Squibb, India','mahesh-iyer','https://www.linkedin.com/in/mahesh-iyer-9b5ba64/'),
 (33,'naveen-sivadasan','Dr. Naveen Sivadasan','Principal Scientist & Head of Life Sciences Research','TCS Research','naveen-sivadasan','https://www.linkedin.com/in/naveen-sivadasan-b71027b2/'),
 (34,'s-k-menon','Shashikumar Menon','Former CEO','Muralya','s-k-menon',''),
 (35,'d-g-namboothiri','D. G. Namboothiri','General Manager (R&D)','Sreedhareeyam Ayurvedic Eye Hospital & Research Centre','d-g-namboothiri','https://www.linkedin.com/in/d-g-namboodiri-6520b319/'),
 (36,'rajmohan-v','Dr. Rajmohan V.','Associate Professor','Government Ayurveda College, Thiruvananthapuram','rajmohan-v','https://www.linkedin.com/in/dr-rajmohan-v-520447206/'),
 (37,'venkatachalam','Venkatachalam','Founder & CEO','Certitude Farms','venkatachalam','https://www.linkedin.com/in/balasubramaniam-v-66603639/'),
 (38,'mrutyunjay-suar','Dr. Mrutyunjay Suar','Director General, Industry Institute Innovation Interface','KIIT University','mrutyunjay-suar','https://www.linkedin.com/in/mrutyunjay-suar-phd-7981a114/'),
 (39,'k-ampady','Dr. K. Ampady','Chief Executive Officer','KRIBS-BioNest','k-ampady','https://www.linkedin.com/in/ampady-k-7606b3119/'),
 (40,'ashish-g-r','Dr. Ashish G. R.','Principal Scientist','Vaidyaratnam Group','ashish-g-r','');
