package app

import (
	"bytes"
	"context"
	"encoding/json"
	"image"
	"io/fs"
	"strings"
	"testing"
)

// The artwork is generated by registration/artwork/compose.py and committed.
// These checks are what stops a half-finished regeneration - a renamed motif,
// a spec pointing at a PNG that was never written, a size table edited without
// rebuilding - from shipping as a studio full of broken templates.
func TestEmbeddedPosterArtworkIsConsistent(t *testing.T) {
	specs, err := fs.Glob(posterArt, "artwork/specs/*.json")
	if err != nil {
		t.Fatal(err)
	}
	if len(specs) == 0 {
		t.Fatal("no poster specs embedded; run artwork/compose.py")
	}

	seenPNG := map[string]bool{}
	for _, name := range specs {
		raw, err := posterArt.ReadFile(name)
		if err != nil {
			t.Fatal(err)
		}
		var s seedSpec
		if err = json.Unmarshal(raw, &s); err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		dim, ok := posterSizes[s.Size]
		if !ok {
			t.Errorf("%s: unknown size %q", name, s.Size)
			continue
		}
		if s.Family == "" || s.Name == "" {
			t.Errorf("%s: family and name are required", name)
		}

		// Both artwork layers must exist, be PNG, and be exactly the canvas
		// size the spec's layers were laid out against.
		body := string(s.Spec)
		for placeholder, role := range map[string]string{"__BACKDROP__": "backdrop", "__OVERLAY__": "overlay"} {
			if !strings.Contains(body, placeholder) {
				t.Errorf("%s: spec does not reference %s", name, placeholder)
				continue
			}
			path := "artwork/" + s.Family + "-" + s.Size + "-" + role + ".png"
			b, err := posterArt.ReadFile(path)
			if err != nil {
				t.Errorf("%s: %s missing: %v", name, path, err)
				continue
			}
			seenPNG[path] = true
			cfg, format, err := image.DecodeConfig(bytes.NewReader(b))
			if err != nil {
				t.Errorf("%s: undecodable: %v", path, err)
				continue
			}
			if format != "png" {
				t.Errorf("%s: format %s, want png", path, format)
			}
			if cfg.Width != dim[0] || cfg.Height != dim[1] {
				t.Errorf("%s: %dx%d, want %dx%d", path, cfg.Width, cfg.Height, dim[0], dim[1])
			}
			// Nothing should be so large that a browser struggles to composite
			// several of them, and the upload path caps at 8 MB.
			if len(b) > posterUploadMax {
				t.Errorf("%s: %d bytes exceeds the poster upload cap", path, len(b))
			}
			body = strings.ReplaceAll(body, placeholder, "0123456789abcdef0123456789abcdef")
		}

		// The spec must survive the same validation a staff-built one does.
		spec, err := validateSpec(json.RawMessage(body), dim[0], dim[1])
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}

		// The event furniture is what makes a template usable without retyping
		// the venue on every poster.
		for _, key := range []string{"tagline", "dates", "month", "venue", "website", "qr_url"} {
			if spec.Defaults[key] == "" {
				t.Errorf("%s: no default for %q", name, key)
			}
		}
		if got := spec.Defaults["qr_url"]; !strings.HasPrefix(got, "https://") {
			t.Errorf("%s: qr_url default %q is not https", name, got)
		}
		// A QR layer's payload must reach the encoder, which rejects anything
		// that is not an https URL.
		for _, l := range spec.Layers {
			if l.Type == "qr" && spec.Defaults[l.Key] == "" {
				t.Errorf("%s: QR layer %q has no default payload", name, l.ID)
			}
		}
	}

	// No orphan artwork: every embedded PNG should belong to some spec, or the
	// binary is carrying megabytes nothing can reach.
	all, err := fs.Glob(posterArt, "artwork/*.png")
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range all {
		if !seenPNG[path] {
			t.Errorf("%s is embedded but no spec references it", path)
		}
	}
	if len(specs) != len(all)/2 {
		t.Errorf("%d specs but %d PNGs; expected two layers each", len(specs), len(all))
	}
}

// A deploy must not undo a layout staff changed in the builder, and rolling out
// new artwork must not leave the studio half-updated.
func TestSeedPostersIsIdempotentAndPreservesStaffEdits(t *testing.T) {
	a := mustApp(t)
	ctx := context.Background()

	first, err := a.SeedPosters(ctx, false)
	if err != nil {
		t.Fatalf("first seed: %v", err)
	}
	if len(first) == 0 {
		t.Fatal("seeded nothing")
	}
	for _, r := range first {
		if r.Status != "created" {
			t.Errorf("%s %s: %s on a clean database, want created", r.Family, r.Size, r.Status)
		}
	}
	active := count(t, a, "SELECT count(*) FROM poster_templates WHERE active")
	if active != len(first) {
		t.Fatalf("%d active templates after seeding %d", active, len(first))
	}

	// Re-running keeps everything, and uploads no second copy of any asset.
	assets := count(t, a, "SELECT count(*) FROM poster_assets")
	second, err := a.SeedPosters(ctx, false)
	if err != nil {
		t.Fatalf("second seed: %v", err)
	}
	for _, r := range second {
		if r.Status != "kept" {
			t.Errorf("%s %s: %s on a re-run, want kept", r.Family, r.Size, r.Status)
		}
	}
	if n := count(t, a, "SELECT count(*) FROM poster_assets"); n != assets {
		t.Errorf("re-run changed the asset count from %d to %d", assets, n)
	}
	if n := count(t, a, "SELECT count(*) FROM poster_templates WHERE active"); n != active {
		t.Errorf("re-run changed the active template count from %d to %d", active, n)
	}

	// --replace rolls new artwork out, still without duplicating assets whose
	// bytes have not changed.
	third, err := a.SeedPosters(ctx, true)
	if err != nil {
		t.Fatalf("replace seed: %v", err)
	}
	for _, r := range third {
		if r.Status != "replaced" {
			t.Errorf("%s %s: %s with replace, want replaced", r.Family, r.Size, r.Status)
		}
	}
	if n := count(t, a, "SELECT count(*) FROM poster_assets"); n != assets {
		t.Errorf("replace duplicated assets: %d -> %d", assets, n)
	}
	if n := count(t, a, "SELECT count(*) FROM poster_templates WHERE active"); n != active {
		t.Errorf("replace left %d active templates, want %d", n, active)
	}
	// The partial unique index only permits one active row per family and size,
	// so the superseded ones must have been retired rather than deleted.
	if n := count(t, a, "SELECT count(*) FROM poster_templates WHERE NOT active"); n != active {
		t.Errorf("%d retired templates after one replace, want %d", n, active)
	}

	// Seeded templates carry usable asset ids, not the build placeholders.
	var spec string
	if err := a.DB.QueryRow(ctx,
		"SELECT spec::text FROM poster_templates WHERE active ORDER BY family,size LIMIT 1").Scan(&spec); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(spec, "__BACKDROP__") || strings.Contains(spec, "__OVERLAY__") {
		t.Error("a seeded spec still contains artwork placeholders")
	}
	var refs int
	if err := a.DB.QueryRow(ctx, `
		SELECT count(*) FROM poster_templates t
		CROSS JOIN LATERAL jsonb_array_elements(t.spec->'layers') l
		WHERE t.active AND l->>'type'='art'
		  AND NOT EXISTS (SELECT 1 FROM poster_assets WHERE id = l->>'asset_id')`).Scan(&refs); err != nil {
		t.Fatal(err)
	}
	if refs != 0 {
		t.Errorf("%d seeded art layers point at a missing asset", refs)
	}
}
