#!/usr/bin/env python3
"""Write the published programme into programme.html.

The programme is edited in the staff console's Mobile app editor (Programme)
and stored in the registration backend, which also feeds the mobile app. This
script renders it into the generated regions of programme.html, so the page is
plain static HTML: indexable, fast, and working without JavaScript.
scripts/deploy.sh runs it after scripts/sync-speakers.py, whose portraits it
reuses for speakers linked to the directory.

Usage:
    python3 scripts/sync-programme.py [--api URL] [--check]

--check exits 1 without writing anything when the page is out of date.

script.js renders the same markup from the live API when the programme has
changed since the last deploy (renderProgramme); keep the two in step.
"""
import argparse
import html
import json
import re
import sys
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "programme.html"
SPEAKERS_PAGE = ROOT / "speakers.html"
API = "https://reg.bioconnect.kerala.gov.in/api/v1/public/event-guide?include=breaks"
IST = timezone(timedelta(hours=5, minutes=30))

NAV = ("<!-- programme-nav:begin (generated by scripts/sync-programme.py) -->", "<!-- programme-nav:end -->")
LIST = ("<!-- programme:begin (generated by scripts/sync-programme.py) -->", "<!-- programme:end -->")

KIND_LABELS = {"talk": "Talk", "panel": "Panel discussion", "ceremony": "Ceremony", "social": "Evening programme", "break": "Break"}
ROLE_GROUPS = [("moderator", "Moderator", "Moderators"), ("panelist", "Panellist", "Panellists"), ("host", "Host", "Hosts")]
HONORIFICS = re.compile(r"\b(dr|prof|mr|mrs|ms|shri|smt|padma bhushan|padma shri|ias)\b\.?", re.I)
BREAK_ICONS = {
    "meal": '<path d="M7 3v8a2 2 0 0 0 2 2v8M11 3v8M7 7h4M17 21V3c-2 1-3 4-3 8h3" />',
    "badge": '<rect x="4" y="6" width="16" height="14" rx="2" /><path d="M9 6V4h6v2M8 12h8M8 16h5" />',
    "cup": '<path d="M4 9h13v5a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5V9ZM17 11h1.5a2.5 2.5 0 0 1 0 5H17M8 3v3M12 3v3" />',
}


def fetch(url, limit=5 << 20):
    req = urllib.request.Request(url, headers={"User-Agent": "bioconnect-site-build"})
    with urllib.request.urlopen(req, timeout=30) as res:
        body = res.read(limit + 1)
    if len(body) > limit:
        sys.exit(f"{url} is larger than {limit} bytes")
    return body


def esc(value):
    return html.escape(value, quote=True)


def parse(value):
    return datetime.fromisoformat(value).astimezone(IST) if value else None


def clock(moment):
    """2:00 pm, as the organisers print it."""
    return f"{moment.hour % 12 or 12}:{moment.minute:02d} {'am' if moment.hour < 12 else 'pm'}"


def initials(name):
    words = [w for w in re.split(r"[\s.]+", HONORIFICS.sub(" ", name)) if w and w[0].isalpha()]
    if not words:
        return ""
    return (words[0][0] + (words[-1][0] if len(words) > 1 else "")).upper()


def portraits_from_speakers_page():
    """Speaker ID -> portrait path, from the cards sync-speakers.py wrote."""
    page = SPEAKERS_PAGE.read_text(encoding="utf-8")
    cards = re.findall(r'data-speaker-id="([^"]+)">\s*<div class="speaker-portrait">\s*<img src="([^"]+)"', page)
    return {html.unescape(i): html.unescape(src) for i, src in cards}


def time_block(start, end, indent):
    if not start:
        return f'{indent}<p class="prog-time"><span class="prog-tbc">Time to be confirmed</span></p>'
    out = f'{indent}<p class="prog-time"><time datetime="{start.isoformat()}">{clock(start)}</time>'
    if end:
        out += f'<span class="prog-end">to <time datetime="{end.isoformat()}">{clock(end)}</time></span>'
    return out + "</p>"


def person(p, portraits, indent):
    sid = p.get("speaker_id", "")
    text = f'<span class="prog-person-text"><span class="prog-person-name">{esc(p["name"])}</span>'
    if p.get("designation"):
        text += f'<span class="prog-person-role">{esc(p["designation"])}</span>'
    text += "</span>"
    if sid:
        body = f'<a class="prog-person-link" href="speakers.html#{esc(sid)}" data-speaker-id="{esc(sid)}">{avatar(p, portraits)}{text}</a>'
    else:
        body = f'<span class="prog-person-link">{avatar(p, portraits)}{text}</span>'
    return f'{indent}<li class="prog-person">{body}</li>'


def avatar(p, portraits):
    src = portraits.get(p.get("speaker_id", ""), "")
    if src:
        return f'<span class="prog-avatar"><img src="{esc(src)}" width="480" height="600" alt="" loading="lazy" decoding="async" /></span>'
    return f'<span class="prog-avatar" aria-hidden="true">{esc(initials(p["name"]))}</span>'


def solo_speaker(session, portraits, indent):
    """A keynote titled with its speaker's name: the speaker is the heading."""
    p, sid = session["people"][0], session["people"][0].get("speaker_id", "")
    text = f'<div class="prog-solo-text"><h3 class="prog-title" id="t-{esc(session["id"])}">{esc(p["name"])}</h3>'
    if p.get("designation"):
        text += f'<p class="prog-person-role">{esc(p["designation"])}</p>'
    text += "</div>"
    if sid:
        return f'{indent}<a class="prog-solo" href="speakers.html#{esc(sid)}" data-speaker-id="{esc(sid)}">{avatar(p, portraits)}{text}</a>'
    return f'{indent}<div class="prog-solo">{avatar(p, portraits)}{text}</div>'


def people_groups(session, portraits, indent):
    people = session["people"]
    speaking = [p for p in people if p.get("role", "") not in ("moderator", "panelist", "host")]
    one, many = ("In conversation", "In conversation") if session["kind"] == "panel" else ("Speaker", "Speakers")
    groups = [(one if len(speaking) == 1 else many, speaking)]
    for role, single, plural in ROLE_GROUPS:
        members = [p for p in people if p.get("role", "") == role]
        groups.append((single if len(members) == 1 else plural, members))
    lines = [f'{indent}<div class="prog-people">']
    for title, members in groups:
        if not members:
            continue
        lines.append(f'{indent}  <div class="prog-group">')
        lines.append(f'{indent}    <p class="prog-role">{esc(title)}</p>')
        lines.append(f'{indent}    <ul class="prog-persons">')
        lines += [person(p, portraits, indent + "      ") for p in members]
        lines.append(f"{indent}    </ul>")
        lines.append(f"{indent}  </div>")
    lines.append(f"{indent}</div>")
    return lines


def running_order(segments, portraits, indent):
    timed = sum(1 for g in segments if g.get("starts_at"))
    lines = [
        f'{indent}<details class="prog-order">',
        f'{indent}  <summary>Running order <span>{timed} {"item" if timed == 1 else "items"}</span></summary>',
        f'{indent}  <ol class="prog-order-list">',
    ]
    for g in segments:
        start = parse(g.get("starts_at"))
        when = f'<time datetime="{start.isoformat()}">{clock(start)}</time>' if start else '<span class="prog-order-untimed" aria-hidden="true"></span>'
        lines.append(f'{indent}    <li class="prog-order-item{"" if start else " prog-order-note-only"}">')
        lines.append(f"{indent}      {when}")
        lines.append(f'{indent}      <div class="prog-order-body">')
        lines.append(f'{indent}        <p class="prog-order-title">{esc(g["title"])}</p>')
        if g.get("description"):
            lines.append(f'{indent}        <p class="prog-order-note">{esc(g["description"])}</p>')
        if g.get("people"):
            lines.append(f'{indent}        <ul class="prog-persons prog-persons-compact">')
            lines += [person(p, portraits, indent + "          ") for p in g["people"]]
            lines.append(f"{indent}        </ul>")
        lines.append(f"{indent}      </div>")
        lines.append(f"{indent}    </li>")
    lines += [f"{indent}  </ol>", f"{indent}</details>"]
    return lines


def when_attr(start, end):
    """A break's times, shown inside its band where the time column is hidden."""
    if not start:
        return ""
    return f' data-when="{clock(start)}{f" - {clock(end)}" if end else ""}"'


def break_icon(title):
    t = title.lower()
    key = "meal" if ("lunch" in t or "dinner" in t) else "badge" if "registration" in t else "cup"
    return f'<svg class="prog-break-icon" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">{BREAK_ICONS[key]}</svg>'


def item(session, portraits, indent):
    s = session
    start, end = parse(s["starts_at"]), parse(s["ends_at"])
    attrs = f'data-kind="{esc(s["kind"] or "session")}"'
    if start and end:
        attrs += f' data-start="{start.isoformat()}" data-end="{end.isoformat()}"'
    if s["kind"] == "break":
        return [
            f'{indent}<li class="prog-item prog-break" {attrs}>',
            time_block(start, end, indent + "  "),
            f'{indent}  <p class="prog-break-body"{when_attr(start, end)}>{break_icon(s["title"])}<span>{esc(s["title"])}</span></p>',
            f"{indent}</li>",
        ]
    label = s["label"] or KIND_LABELS.get(s["kind"], "Session")
    solo = s["kind"] == "talk" and len(s["people"]) == 1 and not s["segments"] and s["people"][0]["name"] == s["title"]
    i2, i3 = indent + "  ", indent + "    "
    lines = [
        f'{indent}<li class="prog-item" id="s-{esc(s["id"])}" {attrs}>',
        time_block(start, end, i2),
        f'{i2}<article class="prog-card" aria-labelledby="t-{esc(s["id"])}">',
    ]
    track = f' <span class="prog-track">{esc(s["track"])}</span>' if s["track"] else ""
    lines.append(f'{i3}<p class="prog-label"><span class="prog-live" hidden>Now</span>{esc(label)}{track}</p>')
    if solo:
        lines.append(solo_speaker(s, portraits, i3))
    else:
        lines.append(f'{i3}<h3 class="prog-title" id="t-{esc(s["id"])}">{esc(s["title"])}</h3>')
    if s["description"]:
        lines.append(f'{i3}<p class="prog-desc">{esc(s["description"])}</p>')
    if s["location"]:
        lines.append(f'{i3}<p class="prog-where">{esc(s["location"])}</p>')
    if s["people"] and not solo:
        lines += people_groups(s, portraits, i3)
    if s["segments"]:
        lines += running_order(s["segments"], portraits, i3)
    lines += [f"{i2}</article>", f"{indent}</li>"]
    return lines


def by_day(sessions):
    """Sessions grouped by IST day in programme order; untimed ones last."""
    def key(pair):
        i, s = pair
        start, end = parse(s["starts_at"]), parse(s["ends_at"])
        return (start is None, start or datetime.max.replace(tzinfo=IST), end or datetime.max.replace(tzinfo=IST), s["title"] if start is None else "", i)
    days = {}
    for _, s in sorted(enumerate(sessions), key=key):
        start = parse(s["starts_at"])
        days.setdefault(start.date() if start else None, []).append(s)
    return list(days.items())


def day_meta(n, day):
    if day is None:
        return "day-tbc", "Later", "Time to be confirmed", "To be confirmed"
    return f"day-{n}", f"Day {n}", f"{day:%A} {day.day} {day:%B}", f"{day:%a} {day.day} {day:%b}"


def render_list(sessions, portraits):
    out = []
    indent = "          "
    for n, (day, items) in enumerate(by_day(sessions), 1):
        anchor, number, title, _ = day_meta(n, day)
        out += [
            f'{indent}<section class="prog-day" id="{anchor}" aria-labelledby="{anchor}-title">',
            f'{indent}  <header class="prog-day-head">',
            f'{indent}    <p class="prog-day-num">{number}</p>',
            f'{indent}    <h2 class="prog-day-title" id="{anchor}-title">{title}</h2>',
            f"{indent}  </header>",
            f'{indent}  <ol class="prog-list">',
        ]
        for s in items:
            out += item(s, portraits, indent + "    ")
        out += [f"{indent}  </ol>", f"{indent}</section>"]
    return "\n".join(out)


def render_nav(sessions):
    indent = "            "
    links = []
    for n, (day, _) in enumerate(by_day(sessions), 1):
        anchor, number, _, short = day_meta(n, day)
        links.append(f'{indent}<a class="prog-daylink" href="#{anchor}"><strong>{number}</strong><span>{short}</span></a>')
    return "\n".join(links)


def replace_region(page, region, body, indent):
    begin, end = region
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if len(pattern.findall(page)) != 1:
        sys.exit(f"programme.html: expected exactly one {begin} ... {end} region")
    return pattern.sub(lambda _: f"{begin}\n{body}\n{indent}{end}", page)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--api", default=API)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    guide = json.loads(fetch(args.api))
    sessions = guide.get("sessions")
    if not isinstance(sessions, list) or not sessions:
        # Never blank the page (or block a deploy) because nothing is published.
        print("warning: the event guide has no published sessions; programme.html left unchanged", file=sys.stderr)
        return
    for s in sessions:
        for key in ("kind", "label", "track", "description", "location", "starts_at", "ends_at"):
            s.setdefault(key, "")
        s.setdefault("people", [])
        s.setdefault("segments", [])

    page = PAGE.read_text(encoding="utf-8")
    portraits = portraits_from_speakers_page()
    new = replace_region(page, NAV, render_nav(sessions), "            ")
    new = replace_region(new, LIST, render_list(sessions, portraits), "          ")
    new, n = re.subn(r'data-programme-revision="[^"]*"', f'data-programme-revision="{int(guide.get("revision", 0))}"', new)
    if n != 1:
        sys.exit("programme.html: data-programme-revision not found")
    if new == page:
        print("programme.html is up to date")
        return
    if args.check:
        sys.exit("out of date: programme.html; run scripts/sync-programme.py")
    PAGE.write_text(new, encoding="utf-8")
    print(f"updated programme.html ({len(sessions)} sessions, revision {guide.get('revision')})")


if __name__ == "__main__":
    main()
