#!/usr/bin/env python3
"""Write the published speaker list into the static website.

The registration backend's speaker list (edited in the staff console's Mobile
app editor) is the single source of truth for the mobile app, the staff
console and this site. This script renders it into the generated regions of
speakers.html and the home page's speakers teaser, and copies every portrait
into assets/speakers/, so the pages stay plain static HTML: indexable, fast,
and working without JavaScript. scripts/deploy.sh runs it before uploading.

Usage:
    python3 scripts/sync-speakers.py [--api URL] [--check]

--check exits 1 without writing anything when a page is out of date.

Portraits already on the site keep their file. A portrait uploaded through the
editor is downloaded once and saved under a name carrying its content hash,
so a replaced portrait gets a new URL and no cache can serve the old one.
"""
import argparse
import hashlib
import html
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://bioconnect.kerala.gov.in"
API = "https://reg.bioconnect.kerala.gov.in/api/v1/public/speakers"
PORTRAITS = ROOT / "assets" / "speakers"
SITE_PORTRAITS = SITE + "/assets/speakers/"
WIDTH, HEIGHT = 480, 600
TEASER_FACES = 5

BEGIN, END = "<!-- speakers:begin (generated by scripts/sync-speakers.py) -->", "<!-- speakers:end -->"
TEASER_BEGIN, TEASER_END = "<!-- speaker-faces:begin (generated by scripts/sync-speakers.py) -->", "<!-- speaker-faces:end -->"


def fetch(url, limit=5 << 20):
    req = urllib.request.Request(url, headers={"User-Agent": "bioconnect-site-build"})
    with urllib.request.urlopen(req, timeout=30) as res:
        body = res.read(limit + 1)
    if len(body) > limit:
        sys.exit(f"{url} is larger than {limit} bytes")
    return body


def text(value):
    return html.escape(value, quote=False)


def attr(value):
    return html.escape(value, quote=True)


def portrait_file(speaker, write):
    """Return the portrait's file name in assets/speakers/, fetching it if new."""
    url = speaker["image_url"]
    if not url:
        sys.exit(f"speaker {speaker['id']} has no portrait; upload one in the Mobile app editor")
    if url.startswith(SITE_PORTRAITS):
        name = url[len(SITE_PORTRAITS):]
        if "/" in name or not (PORTRAITS / name).is_file():
            sys.exit(f"speaker {speaker['id']}: {url} is not a file in assets/speakers/")
        return name
    body = fetch(url)
    name = f"{speaker['id']}-{hashlib.sha256(body).hexdigest()[:10]}.webp"
    path = PORTRAITS / name
    if not path.exists():
        if not write:
            sys.exit(f"out of date: portrait {path.relative_to(ROOT)} is missing; run scripts/sync-speakers.py")
        path.write_bytes(to_webp(body, url))
        print(f"added portrait {path.relative_to(ROOT)}")
    return name


def to_webp(body, url):
    """Editor uploads are already 480 x 600 WebP; anything else is fitted."""
    if body[:4] == b"RIFF" and body[8:12] == b"WEBP" and webp_size(body) == (WIDTH, HEIGHT):
        return body
    try:
        from PIL import Image, ImageOps
    except ImportError:
        sys.exit(f"{url} needs converting to a 480 x 600 WebP; install Pillow (pip install pillow)")
    im = ImageOps.fit(ImageOps.exif_transpose(Image.open(io.BytesIO(body))).convert("RGB"), (WIDTH, HEIGHT), Image.LANCZOS, centering=(0.5, 0.3))
    out = io.BytesIO()
    im.save(out, "WEBP", quality=82, method=6)
    return out.getvalue()


def webp_size(body):
    chunk = body[12:16]
    if chunk == b"VP8 ":
        return int.from_bytes(body[26:28], "little") & 0x3FFF, int.from_bytes(body[28:30], "little") & 0x3FFF
    if chunk == b"VP8L":
        bits = int.from_bytes(body[21:25], "little")
        return (bits & 0x3FFF) + 1, ((bits >> 14) & 0x3FFF) + 1
    if chunk == b"VP8X":
        return int.from_bytes(body[24:27], "little") + 1, int.from_bytes(body[27:30], "little") + 1
    return None


def card(speaker, portrait):
    name = text(speaker["name"])
    lines = [
        f'            <li class="speaker reveal" data-speaker-id="{attr(speaker["id"])}">',
        '              <div class="speaker-portrait">',
        f'                <img src="assets/speakers/{attr(portrait)}" width="480" height="600" alt="" loading="lazy" decoding="async" />',
        "              </div>",
        '              <div class="speaker-meta">',
        f'                <h3 class="speaker-name">{name}</h3>',
        f'                <p class="speaker-role">{text(speaker["role"])}</p>',
        f'                <p class="speaker-org">{text(speaker["organization"])}</p>',
    ]
    if speaker["linkedin"]:
        lines += [
            '                <div class="speaker-actions">',
            f'                  <a class="speaker-linkedin" href="{attr(speaker["linkedin"])}" target="_blank" rel="noopener noreferrer">',
            '                    <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" focusable="false"><use href="#icon-linkedin" /></svg>',
            f'                    <span class="sr-only">{name} on LinkedIn (opens in a new tab)</span>',
            "                  </a>",
            "                </div>",
        ]
    lines += ["              </div>", "            </li>"]
    return "\n".join(lines)


def replace_region(page, begin, end, body, indent):
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if len(pattern.findall(page)) != 1:
        sys.exit(f"expected exactly one {begin} ... {end} region")
    return pattern.sub(lambda _: f"{begin}\n{body}\n{indent}{end}", page)


def render_speakers(page, speakers, portraits, version):
    page, n = re.subn(r'(<ul class="speaker-grid"[^>]*?)(?: data-speakers-version="[^"]*")?( data-speaker-grid)', rf'\1 data-speakers-version="{version}"\2', page)
    if n != 1:
        sys.exit("speakers.html: speaker grid not found")
    cards = "\n".join(card(s, portraits[s["id"]]) for s in speakers)
    return replace_region(page, BEGIN, END, cards, "            ")


def render_teaser(page, speakers, portraits):
    """Keep the faces already chosen while those speakers are listed; fill
    any gap with the next speakers in order."""
    region = re.search(re.escape(TEASER_BEGIN) + r"(.*?)" + re.escape(TEASER_END), page, re.S)
    if not region:
        sys.exit("index.html: speaker teaser region not found")
    by_file = {portraits[s["id"]]: s["id"] for s in speakers}
    chosen = [by_file[f] for f in re.findall(r'assets/speakers/([^"]+)"', region.group(1)) if f in by_file]
    for s in speakers:
        if len(chosen) >= TEASER_FACES:
            break
        if s["id"] not in chosen:
            chosen.append(s["id"])
    faces = "\n".join(
        f'              <img src="assets/speakers/{attr(portraits[i])}" width="480" height="600" alt="" loading="lazy" decoding="async" />'
        for i in chosen[:TEASER_FACES]
    )
    return replace_region(page, TEASER_BEGIN, TEASER_END, faces, "              ")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--api", default=API)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    data = json.loads(fetch(args.api))
    speakers, version = data["speakers"], data["version"]
    # An empty list is far more likely a backend fault than the real line-up.
    if not speakers:
        sys.exit("the speaker list is empty; refusing to publish a page without speakers")
    portraits = {s["id"]: portrait_file(s, not args.check) for s in speakers}

    stale = []
    for name, render in (
        ("speakers.html", lambda page: render_speakers(page, speakers, portraits, version)),
        ("index.html", lambda page: render_teaser(page, speakers, portraits)),
    ):
        path = ROOT / name
        page = path.read_text(encoding="utf-8")
        updated = render(page)
        if updated != page:
            stale.append(name)
            if not args.check:
                path.write_text(updated, encoding="utf-8")
    if args.check and stale:
        sys.exit(f"out of date: {', '.join(stale)}; run scripts/sync-speakers.py")
    print(f"{len(speakers)} speakers (version {version}); " + (f"updated {', '.join(stale)}" if stale else "pages already current"))


if __name__ == "__main__":
    main()
